### ISSUE TITLE
Version tag sync

### ISSUE THREAD

**Issue by dotemacs** [swlkr/oksql#4]
Hi, love the library. Thank you

But I noticed that the README talks about **1.2.1** whereas git tag version, as well as the release on Clojars, is at **1.3.1**.

Maybe you can consider using https://github.com/arrdem/lein-git-version to keep them in sync.
Just an idea...

Thanks in any case

**Comment by swlkr** [comment]
Yeah that's a good idea, I'm going to add that in!

**Comment by swlkr** [comment]
I never added it in, BUT I did update the readme to the latest version `1.3.2` 🤷‍♂️
