### ISSUE TITLE
Provide a way for dynamic sql

### ISSUE THREAD

**Issue by DogLooksGood** [swlkr/oksql#6]
thanks for the great work!

there's one thing I noticed that hugsql have a feature called `snip` so that we can use other libraries like `honeysql` to provide the dynamic part. is there any equivalent in oksql?

**Comment by swlkr** [comment]
Hm… dynamic sql, there isn't a way to do that in oksql yet, I have been working extensively on my web framework https://github.com/coast-framework/coast which *does* have dynamic sql generation (https://github.com/coast-framework/coast/blob/master/docs/EDN-Queries.md), and I am thinking about bringing some of that to oksql, but I'm not sure yet

**Comment by swlkr** [comment]
Just going to close this since I wrote a bunch of stuff for dynamic sql in other libs.

I'm open to PRs for dynamic sql in this one though
