### ISSUE TITLE
Documentation: the connection string needs `jdbc:` prepended.

### ISSUE THREAD

**Issue by manzanit0** [swlkr/oksql#7]
I've been playing around with the library, and it's great, but I noticed that there is something misleading in the documentation: the connection string in all the example looks like `postgresql://localhost:5432/some_db`.

In order to make it work I needed to prepend the `jdbc:` string, so it looks like: `jdbc:postgresql://localhost:5432/some_db`. Otherwise you get the famous _SQLException: Driver not found..._

**Comment by swlkr** [comment]
Hey, I fixed that in this commit! Took me a while

Closed by c9f0cb35d367b91d2f9fb5db17e75008840cf115
