### ISSUE TITLE
Upon delete: IllegalStateException: Attempting to call unbound fn

### ISSUE THREAD

**Issue by manzanit0** [swlkr/oksql#8]
Trying to un a quick spike I found that the delete option doesn't work as I expected. Using the example from the documentation where the query is:

```
-- name: delete
-- fn: first
delete
from jobs
where id = :id
returning *
```

The delete function is:
```
(defn delete [id]
  (query :items/delete {:id id}))
```

And the invocation is `(delete 38)` where a record with Id 38 exists, I get the error:

**CompilerException java.lang.IllegalStateException: Attempting to call unbound fn**

Just to clarify, the `database.clj` file I've written is a simple copy paste of the documentation of the repository. Just as well as the `items.sql` file.

**Comment by swlkr** [comment]
I also had a hard time with the delete function, so I changed memoize to call the `get-lines` function directly and it seemed to clear things up

Closed by 7e094ce2e7e53ca68dcb854ecf5c6854f5173900

Reopen if you still have any trouble
